#!/bin/bash

# Copyright (C) 2016-2017 Claudio Luck <claudio.luck@gmail.com>
#
# MIT License

export LANG=C
export LC_ALL=C

function on_exit {
    [ -z "$NF" -o ! -e "$NF" ] || rm -f "$NF"
}
trap on_exit EXIT
NF=$(mktemp)

mkdir -p /etc/nginx/proxy-trusts.pem.d

NGINX_IP=$(ip -o route get 8.8.8.8 | sed -e 's/^.* src //' -e 's/ .*$//')
NGINX_HN=$(getent hosts $NGINX_IP | awk "/^$NGINX_IP/ {print \$2}" | grep -v localhost | tail -n1)

echo "# AUTOGENERATED proxy-trusts.pem" >$NF
echo "# Put certificates in /etc/nginx/proxy-trusts.pem.d" >>$NF
echo "#  and run UPDATE_proxy-trusts.sh" >>$NF
echo "" >>$NF

while read -d $'\0' PEM ; do
    echo "# Source: $(basename $PEM)" >>$NF
    cat $PEM >>$NF
    echo >>$NF
done < <(find /etc/nginx/proxy-trusts.pem.d/ -name \*.pem -print0)

# Always append one more (our own):
for PEM in /etc/pki/tls/certs/${NGINX_HN}.pem /etc/letsencrypt/live/${NGINX_HN}/cert.pem ; do
    [ -r $PEM ] || continue
    echo "# Source: $PEM" >>$NF
    cat $PEM >>$NF
done

if ! cmp --silent $NF /etc/nginx/proxy-trusts.pem ; then
    echo "/etc/nginx/proxy-trusts.pem changed, reloading server"
    mv -f $NF /etc/nginx/proxy-trusts.pem
    chmod 0400 /etc/nginx/proxy-trusts.pem
    chown nginx: /etc/nginx/proxy-trusts.pem
    if which restorecon >/dev/null ; then
        restorecon /etc/nginx/proxy-trusts.pem
    fi
    systemctl reload nginx
fi
